name: 打包部署

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --legacy-peer-deps
        npm run clean
        npm run lint:fix
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        commit_message: ${{ github.event.head_commit.message }}
        commit_author: ${{ github.event.head_commit.author }}
        commit_email: ${{ github.event.head_commit.author_email }}
        commit_time: ${{ github.event.head_commit.timestamp }}
        commit_sha: ${{ github.event.head_commit.id }}
        commit_branch: ${{ github.event.head_commit.branch }}
        commit_tag: ${{ github.event.head_commit.tag }}
        commit_url: ${{ github.event.head_commit.url }}
